from fpdf import FPDF
import os

# Path to Tamil Unicode font (NotoSansTamil)
FONT_DIR = os.path.join(os.path.dirname(__file__), "static")
TAMIL_FONT_PATH = os.path.join(FONT_DIR, "NotoSansTamil.ttf")
TAMIL_SUBJECTS = {"tamil", "தமிழ்", "tamil language", "tamil literature"}

def is_tamil(subject: str) -> bool:
    return subject.strip().lower() in TAMIL_SUBJECTS


class PDFExport(FPDF):
    def __init__(self, use_tamil=False):
        super().__init__()
        self.use_tamil = use_tamil
        if use_tamil and os.path.exists(TAMIL_FONT_PATH):
            self.add_font("NotoTamil", "", TAMIL_FONT_PATH)
            self.add_font("NotoTamil", "B", TAMIL_FONT_PATH)  # bold falls back to same TTF
            self.tamil_available = True
        else:
            self.tamil_available = False

    def _body_font(self, bold=False):
        """Set the appropriate body font depending on language."""
        if self.use_tamil and self.tamil_available:
            self.set_font("NotoTamil", size=11)
        else:
            style = "B" if bold else ""
            self.set_font("Arial", style, 11)

    def _heading_font(self):
        if self.use_tamil and self.tamil_available:
            self.set_font("NotoTamil", size=12)
        else:
            self.set_font("Arial", "B", 12)

    def header(self):
        if self.use_tamil and self.tamil_available:
            self.set_font("NotoTamil", size=14)
        else:
            self.set_font("Arial", "B", 14)
        self.set_fill_color(103, 126, 234)
        self.set_text_color(255, 255, 255)
        self.cell(0, 12, "Study Material - Generated by AI", align="C", new_x="LMARGIN", new_y="NEXT", fill=True)
        self.set_text_color(0, 0, 0)
        self.ln(3)

    def add_section(self, title, content):
        if not content or not content.strip():
            return
        self._heading_font()
        self.set_fill_color(103, 126, 234)
        self.set_text_color(255, 255, 255)
        self.cell(0, 10, title, new_x="LMARGIN", new_y="NEXT", fill=True)
        self.set_text_color(0, 0, 0)
        self.ln(2)
        self._body_font()
        if self.use_tamil and self.tamil_available:
            # Tamil Unicode — write directly, no latin-1 mangling
            self.multi_cell(0, 8, content)
        else:
            safe_content = content.encode("latin-1", "replace").decode("latin-1")
            self.multi_cell(0, 8, safe_content)
        self.ln(5)


def generate_pdf(subject, topic, sections):
    tamil = is_tamil(subject)
    pdf = PDFExport(use_tamil=tamil)
    pdf.add_page()

    # Title
    if tamil and pdf.tamil_available:
        pdf.set_font("NotoTamil", size=16)
    else:
        pdf.set_font("Arial", "B", 16)
    pdf.set_text_color(103, 126, 234)
    pdf.cell(0, 12, f"{subject}", new_x="LMARGIN", new_y="NEXT", align="C")

    if tamil and pdf.tamil_available:
        pdf.set_font("NotoTamil", size=13)
    else:
        pdf.set_font("Arial", "B", 13)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 10, f"Topic: {topic}", new_x="LMARGIN", new_y="NEXT", align="C")
    pdf.ln(5)

    pdf.add_section("1. SUMMARY",                   sections.get("summary", ""))
    pdf.add_section("2. SHORT NOTES",               sections.get("short_notes", ""))
    pdf.add_section("3. PRACTICAL / CODING EXAMPLES", sections.get("coding_examples", ""))
    pdf.add_section("4. IMPORTANT QUESTIONS",       sections.get("important_questions", ""))
    pdf.add_section("5. MCQs",                      sections.get("mcqs", ""))
    pdf.add_section("6. PREVIOUS YEAR QUESTIONS",   sections.get("previous_year_questions", ""))
    pdf.add_section("7. YOUTUBE LINKS",             sections.get("youtube_links", ""))

    safe_name = f"{subject}_{topic}".replace(" ", "_").replace("/", "_")
    filepath = os.path.join("static", f"{safe_name}.pdf")
    pdf.output(filepath)
    return filepath